version: '3'
services:
  # Frontend
    image: nginx:latest
    ports:
      - "9001:80" #container:actual port number
    volumes:
      - nginx-data:/app-data #volume_name:mount_point
      - nginx-backup:/backup-data #volume_name:mount_point


